### ISSUE TITLE
superClipboard is not defined

### ISSUE THREAD

**Issue by Wikunia** [technet/brackets.clipbox#3]
Hi,
I tried your extension and unfortunately I get an error on Ctrl-Alt-V:
line 29 in superclipboard.js

I use:
Linux, Brackets 1.0

**Comment by technet** [comment]
Hi I'm sorry that superclipboard.js is not one of my files, just check the repo, no such file, I think it is from different extension you have installed

**Comment by Wikunia** [comment]
Sorry that was my mistake... it was the various improvements extension which uses the same shortcut.
Thanks for your extension!
